### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "testuser_5",
  "email": "foo5@bar.com",
  "password": "testpassword"
}

### Login with the registered user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identifier": "testuser_5",
  "password": "testpassword"
}

### Logout
POST http://localhost:3000/api/auth/logout
Authorization: Bearer <YOUR_JWT_TOKEN>

### Forgot password
POST http://localhost:3000/api/auth/forgot-password
Content-Type: application/json

{
  "username": "testuser"
}

### Reset password
POST http://localhost:3000/api/auth/reset-password
Content-Type: application/json

{
  "resetPasswordToken": "asdf",
  "password": "newpassword
}